on: [push]

name: Build for Raspberry Pi Zero

jobs:
  linux_arm:
    name: Linux ARMv6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libpq-dev
        run: sudo apt install libpq-dev
      - uses: actions-rs/toolchain@v1
        name: Setup toolchain
        with:
          toolchain: nightly-2020-05-20
          target: arm-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          use-cross: true
          command: build
          args: --target arm-unknown-linux-gnueabihf
